// Mocks generated by Mockito 5.4.6 from annotations
// in petstore_app/test/data/repositories/pet_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:petstore_app/features/pet/data/datasources/pet_remote_datasource.dart'
    as _i3;
import 'package:petstore_app/features/pet/data/models/pet_create_request_model.dart'
    as _i6;
import 'package:petstore_app/features/pet/data/models/pet_model.dart' as _i5;
import 'package:petstore_app/features/pet/data/models/pet_update_request_model.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PetRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRemoteDataSource extends _i1.Mock
    implements _i3.PetRemoteDataSource {
  MockPetRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i4.Future<List<_i5.PetModel>> getAvailablePets(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailablePets, [status]),
            returnValue: _i4.Future<List<_i5.PetModel>>.value(<_i5.PetModel>[]),
          )
          as _i4.Future<List<_i5.PetModel>>);

  @override
  _i4.Future<void> createPet(_i6.PetCreateRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createPet, [request]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePet(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePet(_i7.PetUpdateRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updatePet, [request]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
